Repository otvkatibe/riot-backend, pull requests merged in 2025-07, with the labels that each got.

#38 feat: adicionar suporte a múltiplas regiões nos endpoints da API Riot
  src/services/riot.service.js
Labels: enhancement

#41 Feature/add regions
  src/controller/riot.controller.js
  src/services/riot.service.js
Labels: enhancement

#43 feat: refatorar funções para utilizar URLs base dinâmicas por região
  src/services/riot.service.js
Labels: enhancement

#44 fix: corrigir endpoint para buscar invocador por PUUID
  src/services/riot.service.js
Labels: enhancement

#45 feat: adicionar função para identificar região a partir do PUUID e atualizar chamadas de API
  src/services/riot.service.js
Labels: enhancement

#46 feat: obter dados de ranqueadas utilizando a região identificada a partir do PUUID
  src/controller/riot.controller.js
Labels: enhancement

#47 feat: exportar função getRegionByPuuid para identificar a região a partir do PUUID
  src/services/riot.service.js
Labels: duplicate

#49 feat: atualizar função getProfile para utilizar PUUID ao buscar dados ranqueados
  src/controller/riot.controller.js
Labels: bug

#52 fix
  src/index.js
  src/middlewares/riot.validation.js
  src/services/riot.service.js
  src/swagger.js
Labels: bug, documentation
